name: luciq_cli
description: CLI tool for migrating Flutter projects from Instabug to Luciq SDK
version: 1.0.10
homepage: https://github.com/luciqai/luciq-flutter-sdk
repository: https://github.com/luciqai/luciq-flutter-sdk/tree/master/packages/luciq_cli
documentation: https://docs.luciq.ai/docs/flutter-overview

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  archive: ^4.0.7
  args: ^2.4.2
  http: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  lints: ^3.0.0
  pana: ^0.21.0
  test: ^1.24.0

executables:
  luciq-cli: luciq

assets:
  - bin/luciq_config.json

topics:
  - cli
  - flutter
  - luciq
  - migration
  - sdk

